# Generated by Django 4.1.2 on 2023-06-09 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('keyboards', 'Keyboards'), ('mouses', 'Computer Mouses'), ('monitors', 'Monitors'), ('cameras', 'Cameras'), ('laptops', 'Laptops')], default=1, max_length=255, verbose_name='Category'),
            preserve_default=False,
        ),
    ]
