# Generated by Django 4.1.2 on 2023-06-19 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Keyboards', 'Keyboards'), ('Mouses', 'Computer Mouses'), ('Monitors', 'Monitors'), ('Cameras', 'Cameras'), ('Laptops', 'Laptops')], max_length=255, verbose_name='Category'),
        ),
    ]
